### ISSUE TITLE
Implement Search 

### ISSUE THREAD

**Issue by X39** [ArmA-Studio/ArmA.Studio#11]
There is no word search as of now.
implement that for all text based files

**Comment by dedmen** [comment]
I'd suggest hotkeys like Atom/Sublime
Shift+F search in current file CTRL+SHIFT+F search in all files in project.
Additionally CTRL+T to find and open a file in the solution. With that one doesn't really need a filter/searchbox in the solution explorer

**Comment by dedmen** [comment]
Todo: highlighting searched string in current file

**Comment by trdwll** [comment]
Allow the highlight color to be customizable. :)

**Comment by X39** [comment]
see #35 for further stuff "todo"s, this task is completed
