### ISSUE TITLE
Implement Keybinds

### ISSUE THREAD

**Issue by DeliciousJaffa** [ArmA-Studio/ArmA.Studio#13]
Basic keybinds for basic operations should be implemented.

For example:
- Ctrl + S - Save
- Ctrl + Shift + S - Save All

**Comment by X39** [comment]
CTRL+S is actually already implemented

if it is not functional right now, it got broken in a recent commit

**Comment by DeliciousJaffa** [comment]
The properties for the exe report that my version is 0.1.6290.31151

**Comment by X39** [comment]
saving is working on my end perfectly fine using `CTRL+S`
SaveAll is not yet implemented

can you confirm that saving single documents is working for you using `CTRL+S`? if no, please provide basic system informations + informations your keyboard layout

**Comment by DeliciousJaffa** [comment]
Ctrl+S does not work for me on existing files or files created in ArmA Studio

OS: Windows 10 Pro
Language: English (United Kingdom)
Keyboard Layout: United Kingdom

**Comment by DeliciousJaffa** [comment]
Sorry about this, it's something local to my PC. Not working on notepad++ either.

**Comment by X39** [comment]
ok :)
