### ISSUE TITLE
Implement Version Dialog

### ISSUE THREAD

**Issue by DeliciousJaffa** [ArmA-Studio/ArmA.Studio#14]
Include a dialog under the help tab to show the current version (Git commit is ideal)
Or alternatively show the version in the title.

This should make it easier to determine if specific commits have broken anything when supporting end users.

**Comment by dedmen** [comment]
Wanted to suggest version in title too before alpha release apparently I forgot to say it :D

**Comment by X39** [comment]
Added via ' About' dialog

available in https://github.com/X39/ArmA.Studio/tree/Plugin-System branch
