### ISSUE TITLE
Application crash if workspace path contains non latin characters (Cyrillic in my case)

### ISSUE THREAD

**Issue by GunGraveKoga** [ArmA-Studio/ArmA.Studio#16]
Steps to reproduce
==================
1. Execute application 
2. [Workaspace Setup] -> [Select Existing] -> [select folder with Cyrillic name]
3. Press Ok button

Issues
======
Application just crashes, without error message
Invalid path string stores in App.ini config and ArmAStudio crashes on every execution try

**Comment by X39** [comment]
did not receive a crash log sadly ...
could you please check your windows EventLog for the crash and attach the stacktrace to this ticket?
(an example path also would be appreciated :3)
