### ISSUE TITLE
Distinguish between global and local variables

### ISSUE THREAD

**Issue by DeliciousJaffa** [ArmA-Studio/ArmA.Studio#17]
Notepad++ and KK's Arma syntax highlighter currently show a difference between Global and Local variables.
I believe it would be a good idea to implement or test that same idea in ArmA.Studio as it can make reading and interpreting an SQF file easier
![](https://ss.jaffa.cat/2017-03/qk1MuE.png)

**Comment by dedmen** [comment]
I also suggested additional color for private local variables. But not sure if that's useful.

**Comment by jonpas** [comment]
> I also suggested additional color for private local variables. But not sure if that's useful.

I see no need for that, all local variables should be privatized anyways. If anything I'd add a note about unprivatized variables. 😆

**Comment by X39** [comment]
i accept ideas for default colors at any time

**Comment by X39** [comment]
Requires upgrading the xshd xml from https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Highlighting/Xshd/V1Loader.cs to https://github.com/icsharpcode/AvalonEdit/blob/master/ICSharpCode.AvalonEdit/Highlighting/Xshd/V2Loader.cs
