### ISSUE TITLE
Switching Workspace with open Tabs

### ISSUE THREAD

**Issue by vabene1111** [ArmA-Studio/ArmA.Studio#29]
## Steps to reproduce
1. Open some file in current workspace
2. Switch Workspace to another Folder that does not have a file like the one that you opened in 1.
3. Open Solution explorer

## Issues
* While step 2: An [Error Message](https://drive.google.com/uc?id=0B_TmB6GeWD7POVZoRHZ5RFI5ZWc) pops up telling you that the file that was opened in step 1 does not exist. If you try to open the Solution Explorer after that it wont open.
Also: If the solution explorer was open before switching Workspaces it will be closed.

### Expected
* While step 3: Solution explorer should open

## Additional Notes
* The Problem can be fixed by simply restarting once, after that it seems to be required to press "Solution Explorer" **twice** before it works

**Comment by X39** [comment]
Cannot reproduce in head
