### ISSUE TITLE
Create Error Popup displaying the current debugger error

### ISSUE THREAD

**Issue by X39** [ArmA-Studio/ArmA.Studio#36]
something like 
![http://imgur.com/2Wrc4f3](http://i.imgur.com/2Wrc4f3.png)

**Comment by dedmen** [comment]
![img](http://image.prntscr.com/image/bf8037c97d8c4cd6bab3e0126486d0c3.png)
"<filename> triggered script error" instead of "triggered a breakpoint" 
although we could also use that dialog for script Assert's
