### ISSUE TITLE
[DISCORD ISSUE] Startup Window size Hang

### ISSUE THREAD

**Issue by vabene1111** [ArmA-Studio/ArmA.Studio#39]
- next issue: i added my two main folders (quiet a few files, large git history) and when closing, starting its doing the initial lint and then just showing the loading screen for what seems forever

- https://gist.github.com/vabene1111/31230bb168829cb402d4a3dce7d25c32

- Window size is bugged.. And it tries to set "TOP" to "215333333333333" which is > than maxInt32
Window position on startup is always wrong for me. always too high

- ok 1. select workspace -> small window -> close/reopen works, 2. open, maximize -> close -> open: windows is on wrong monitor in fullscren, then moving to main monitor -> closing -> opening -> bug

**Comment by X39** [comment]
cannot reproduce 3 & 4
