### ISSUE TITLE
Open Workspace with deleted files

### ISSUE THREAD

**Issue by vabene1111** [ArmA-Studio/ArmA.Studio#41]
## Steps to reproduce
1. Select and open workspace
2. Close ArmA.Studio
3. Delete some Files
4. Start ArmA.Studio

## Issues
* While step 4: errors pop up for missing files 
e.g. ![](https://drive.google.com/uc?id=0B_TmB6GeWD7PcldMS3BBMHdJdDA)

### Expected
* While step 2: no errors :)

## Notes
You can just click OK for each missing file and ArmA.Studio will start without a problem

**Comment by vabene1111** [comment]
EDIT:
It also does not update the Solution properly, meaning that the deleted Folders/Files will still show in the solution explorer

**Comment by X39** [comment]
not that much of a bug but currently intended design
in later stages, the IDE will watch the FileSystem for theese changes and alter the projects accordingly
they also would display that they are missing

right now, this is not implemented due to low priority and being time intensive

**Comment by X39** [comment]
![unknown](https://user-images.githubusercontent.com/1886428/28129425-8fa3cc18-6733-11e7-893c-3e7833f0de16.png)

**Comment by X39** [comment]
message will still pop up at linting time
gonna "fix" that by altering the behavior, gathering the missing files and then reporting it to the user

please note that they still wont be removed, just be displayed with the "WARNING" icon

**Comment by X39** [comment]
Messages won't pop up anymore for missing files
