### ISSUE TITLE
Add Auto-Download&Install of the debug DLL

### ISSUE THREAD

**Issue by X39** [ArmA-Studio/ArmA.Studio#42]
For simple usage, a user should not be required to take care of his debugger DLL

goal: implement a system that watches theese things

**Comment by dedmen** [comment]
Downloads for debugger
X64:
https://ci.appveyor.com/api/projects/dedmen/armadebugengine/artifacts/BIDebugEngine/x64/Release/BIDebugEngine.dll?job=Platform:%20x64&branch=master
X86:
https://ci.appveyor.com/api/projects/dedmen/armadebugengine/artifacts/BIDebugEngine/Release/BIDebugEngine.dll?job=Platform:%20X86&branch=master
