### ISSUE TITLE
Add "Add existing items.." and "Add existing folder..." context options for projects

### ISSUE THREAD

**Issue by Zarickan** [ArmA-Studio/ArmA.Studio#43]
Arma Studio currently lacks the ability to add several existing files at once, currently this can only be achieved by adding the files one by one, or editing the .assln file.

Therefore I propose adding two new options, or tweaking the current ones. Either the "Add existing item..." should allow for selecting multiple files, or a new option should be added "Add existing items..." to add multiple items at once.

There should also be an option to add existing folders, which should either add the folder and all its files, or recursively add the folders, and all its files, sub-folders and their files.

**Comment by X39** [comment]
Also to be implemented: rescan of projects via context menu
kind of relates to #44
