### ISSUE TITLE
Autocomplete popup stays open whilte tabbing out

### ISSUE THREAD

**Issue by blackfisch** [ArmA-Studio/ArmA.Studio#58]
## Steps to reproduce
1. Start Tool
2. start typing so that the autocomplete popup opens
3. press Alt + TAB

## Issues
* popup stays open

### Expected
* popup should be closed

## Additional Notes
* ![Screenshot](https://user-images.githubusercontent.com/13716626/28315994-223c304c-6bc1-11e7-8244-5a4c4b032c5b.png)

### Original ###
> ## Steps to reproduce
> 1. Programm starten
> 2. Anfangen zu tippen, dass sich die Variablenübersicht öffnet
> 3 Alt + TAB
> 
> 
> ## Issues
> * Übersicht bleibt geöffnet
> 
> 
> ### Expected
> * Übersicht sollte schließen
> 
> 
> ## Additional Notes
> * ![Screenshot](https://user-images.githubusercontent.com/13716626/28315994-223c304c-6bc1-11e7-8244-5a4c4b032c5b.png)

**Comment by X39** [comment]
fixed in https://github.com/ArmA-Studio/ArmA.Studio/commit/80453fb08329f63267c835748a073df38e74f25a
