### ISSUE TITLE
File shown as changed even when all changes have been reverted

### ISSUE THREAD

**Issue by jonpas** [ArmA-Studio/ArmA.Studio#6]
Version: 0.1.6290.31151

Changing a file, not saving it and then undoing to the start still shows file as changed with the `*` symbol.
Additionally the pop-up to save the file on close also shows after performing the same steps.

Expected result is to remove the `*` from the file tab and not ask for save if file was unchanged in that form.

**Comment by X39** [comment]
expected behaviour

the "unsaved changes" star is currently a flag

will be left open as enhancement for future

**Comment by dedmen** [comment]
After each file change you could check the size of the undoBuffer and if it's empty and the file is equal to the file on disk disable the IsModified flag.

**Comment by X39** [comment]
Done in 0.2 release
