### ISSUE TITLE
All docked panels completely empty after program restart

### ISSUE THREAD

**Issue by jonpas** [ArmA-Studio/ArmA.Studio#7]
Version: 0.1.6290.31151

- Open some panels
- Close ArmA.Studio
- Open ArmA.Studio
- Observe no content in any of the panels (no icons next to panel names either)

**Comment by X39** [comment]
could you provide the data at `%appdata%/ArmA.Studio/`?

**Comment by X39** [comment]
Cannot reproduce in head
