### ISSUE TITLE
Debugger does not attach

### ISSUE THREAD

**Issue by xetra11** [ArmA-Studio/ArmA.Studio#72]
## Steps to reproduce
Steps from the Wiki Article "how to debug"

## Issues
I just cannot attach the debugger. I did everything explained and was sure to download the 64bit .dll file. I followed the steps of the video. Deactivated Mods and Battleeye etc.

### Expected
After I loaded my mission where my script is running in I expected the debugger to be able to attach. But always the error msg appears.

**Comment by dedmen** [comment]
What is "the error msg" and where did you get the debugger dll from?

**Comment by xetra11** [comment]
All Infos from here: https://github.com/ArmA-Studio/ArmA.Studio/wiki/Install-and-use-ArmA.Studio

![image](https://user-images.githubusercontent.com/8149023/41487752-1b6752a4-70ea-11e8-97da-7c56195f28e4.png)

**Comment by dedmen** [comment]
if you got the debugger from there then yeah. Won't work
BI broke the debugger back when Arma.Studio development came to a halt.
The Debugger is currently being updated but doesn't work with the current latest Arma.Studio. A VS Code plugin is in the works.

**Comment by xetra11** [comment]
So I just have to wait for a new release?

**Comment by dedmen** [comment]
If you want the debugger in Arma.Studio yeah. But currently it's unlikely that Arma.Studio will get a new release. The VS Code debugger plugin will probably be done sooner

**Comment by X39** [comment]
Unless interest is somehow again generated, I have to agree

Fairly unlikely

**Comment by xetra11** [comment]
Alright I got you then
