### ISSUE TITLE
Improve styling of VariableView

### ISSUE THREAD

**Issue by X39** [ArmA-Studio/ArmA.Studio#9]
Currently, the variable view is implemented rudimentary ...
enhance it by changing the styling and usability to the variable view of for example Visual Studio

**Comment by dedmen** [comment]
Addition: Seperate window to see formatted strings/functions in a big view. Like VS has.
Functions may even want to be linted and highlighted in that view but.. Dunno about that

**Comment by X39** [comment]
As we do not know the actual conntent, linting should not be done in a "see string" window

**Comment by dedmen** [comment]
Well.. We can know the type of the variable. So we can know if it's supposed to be a function.

**Comment by X39** [comment]
already done
